import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const spaceGrotesk = localFont({
  src: './fonts/SpaceGrotesk-VariableFont_wght.ttf',
  weight: '100 900'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.className} min-h-screen antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
